// Embeds the rendered close-up photos as data URIs in src/js/photos.js.
//   node tools/embed-photos.js <photo_dir>
const fs = require('fs'), path = require('path');
const dir = process.argv[2] || 'photos-final';
const out = {};
for (const f of fs.readdirSync(dir).filter(f => f.endsWith('.jpg')).sort()) {
  out[f.replace('.jpg', '')] = 'data:image/jpeg;base64,' + fs.readFileSync(path.join(dir, f)).toString('base64');
}
const js = '// Generated by tools/embed-photos.js — close-up photos rendered with Blender (tools/photos.py).\nconst PHOTO_DATA = ' + JSON.stringify(out) + ';\n';
fs.writeFileSync(path.join(__dirname, '..', 'src/js/photos.js'), js);
console.log(Object.keys(out).length, 'photos,', (js.length / 1e6).toFixed(2), 'MB');
