// Records every line in tools/lines-ch<N>.json with the free, offline Kokoro
// voice model (via sherpa-onnx), shapes each character with ffmpeg, and writes
// src/js/ch<N>/voicelines.js: a map of "speaker|text" -> embedded MP3.
//   node tools/record-voices.js <chapter> <path-to-kokoro-model-dir> <ffmpeg>
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const { execFileSync } = require('child_process');
const sherpa = require(process.env.SHERPA || 'sherpa-onnx-node');
const [, , CH, MODEL, FFMPEG] = process.argv;
const OUT = path.join(__dirname, 'voice-cache');
fs.mkdirSync(OUT, { recursive: true });

// Kokoro v0.19 speakers: 0 af, 1 af_bella, 2 af_nicole, 3 af_sarah, 4 af_sky,
// 5 am_adam, 6 am_michael, 7 bf_emma, 8 bf_isabella, 9 bm_george, 10 bm_lewis
const CAST = {
  jack:        { sid: 10, speed: 1.0,  pitch: 1.0 },
  narrator:    { sid: 9,  speed: 0.92, pitch: 0.97 },
  control:     { sid: 9,  speed: 0.97, pitch: 0.94, phone: true },
  ilse:        { sid: 8,  speed: 0.93, pitch: 0.97 },
  franz:       { sid: 6,  speed: 0.95, pitch: 0.92 },
  vendor:      { sid: 5,  speed: 0.9,  pitch: 0.88 },
  gateGuard:   { sid: 5,  speed: 0.95, pitch: 0.84 },
  stairGuard:  { sid: 6,  speed: 0.95, pitch: 0.83 },
  officeGuard: { sid: 5,  speed: 1.05, pitch: 0.87 },
  waiter:      { sid: 6,  speed: 1.05, pitch: 1.05 },
  baron:       { sid: 9,  speed: 0.9,  pitch: 0.86 },
};

// Spell foreign words and shouted capitals so the English model says them well.
function speakable(t) {
  const fixes = [
    [/Grüß Gott/g, 'Grooss Gott'], [/Danke schön/g, 'Dunkeh shern'], [/mein Herr/g, 'mine hair'],
    [/Fräulein/g, 'Froyline'], [/Bitte sehr/g, 'Bitteh zair'], [/\bBitte\b/g, 'Bitteh'], [/Servus/g, 'Zervus'],
    [/Dom Pérignon/g, 'Dom Perinyon'], [/Karlskirche/g, 'Karls-keer-kheh'], [/Melange/g, 'Meh-lahnzh'],
    [/STRENG GEHEIM/g, 'streng geh-hime'], [/Abendpost/g, 'Ahbent-post'], [/yoooou/g, 'yooou'], [/toooo/g, 'tooo'],
    [/Obstler/g, 'Obst-ler'], [/Café/g, 'Caffay'], [/\.\.\./g, '…'],
  ];
  for (const [a, b] of fixes) t = t.replace(a, b);
  // Abbreviations make the voice stop dead: spell them out.
  t = t.replace(/\bMr\.? J\. /g, 'Mister J ').replace(/\bMr\. /g, 'Mister ').replace(/\bCol\. /g, 'Colonel ').replace(/\bJ\. /g, 'J ');
  // Trailing-off dots and dashes become a short comma pause.
  t = t.replace(/…\s*/g, ', ').replace(/^,\s*/, '').replace(/\s+—\s+/g, ', ');
  // Join very short sentences to their neighbours with a comma, so fragments
  // like "Tempting. But..." flow as one phrase instead of stop-start.
  const parts = t.split(/(?<=\.)\s+/);
  if (parts.length > 1) {
    const words = x => x.replace(/[^A-Za-z' ]/g, '').trim().split(/\s+/).length;
    t = parts[0];
    for (let i = 1; i < parts.length; i++) {
      const short = words(parts[i - 1]) <= 4 || words(parts[i]) <= 4;
      t = short ? t.replace(/\.$/, ',') + ' ' + parts[i] : t + ' ' + parts[i];
    }
  }
  // ALL-CAPS words (shouting or names) → Title case, so they aren't spelled out.
  t = t.replace(/\b([A-Z]{2,})\b/g, w => w === 'UP' || w === 'AM' ? w.toLowerCase() : w[0] + w.slice(1).toLowerCase());
  return t.replace(/[“”"]/g, '');
}

const tts = new sherpa.OfflineTts({
  model: { kokoro: { model: MODEL + '/model.int8.onnx', voices: MODEL + '/voices.bin', tokens: MODEL + '/tokens.txt', dataDir: MODEL + '/espeak-ng-data' }, numThreads: 4, debug: false },
  maxNumSentences: 2,
});
const lines = JSON.parse(fs.readFileSync(path.join(__dirname, `lines-ch${CH}.json`), 'utf8'));
const out = {};
let n = 0;
for (const { id, text } of lines) {
  const c = CAST[id] || CAST.jack;
  const key = crypto.createHash('sha1').update(JSON.stringify(['v2', c, speakable(text)])).digest('hex').slice(0, 16);
  const mp3 = path.join(OUT, key + '.mp3');
  if (!fs.existsSync(mp3)) {
    const wav = path.join(OUT, key + '.wav');
    const a = tts.generate({ text: speakable(text), sid: c.sid, speed: c.speed });
    sherpa.writeWave(wav, { samples: a.samples, sampleRate: a.sampleRate });
    const f = [];
    if (c.pitch !== 1) f.push(`asetrate=${Math.round(24000 * c.pitch)}`, 'aresample=24000', `atempo=${(1 / c.pitch).toFixed(4)}`);
    f.push('silenceremove=start_periods=1:start_threshold=-50dB:stop_periods=-1:stop_duration=0.3:stop_threshold=-45dB:stop_silence=0.2');
    if (c.phone) f.push('highpass=f=320', 'lowpass=f=3300', 'acompressor=threshold=-22dB:ratio=5:attack=5:release=60', 'volume=1.6');
    f.push('loudnorm=I=-17:TP=-1.5:LRA=9');
    execFileSync(FFMPEG, ['-y', '-loglevel', 'error', '-i', wav, '-af', f.join(','), '-ac', '1', '-ar', '24000', '-b:a', '56k', mp3]);
    fs.unlinkSync(wav);
  }
  out[id + '|' + text] = fs.readFileSync(mp3).toString('base64');
  if (++n % 10 === 0) console.log(`${n}/${lines.length}`);
}
const js = '// Generated by tools/record-voices.js — pre-recorded dialogue (Kokoro, Apache-2.0).\nconst VOICE_LINES = ' + JSON.stringify(out) + ';\n';
fs.writeFileSync(path.join(__dirname, '..', `src/js/ch${CH}/voicelines.js`), js);
console.log('done', n, 'lines,', (js.length / 1e6).toFixed(1), 'MB');
